version: 1.0.{build}
branches:
  only:
    - appveyor
image:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017
  - Ubuntu
install:
  - set QTDIR=C:\Qt\5.5\mingw492_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\Qt\Tools\mingw492_32
build_script:
  - ls %QTDIR%\bin
  - ls C:\Qt\Tools\mingw492_32\bin
  - qmake QtTest.pro
  - mingw32-make
