version: 1.0.{build}
branches:
  only:
    - master
image:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017
  - Ubuntu
install:
  - set QTDIR=C:\Qt\5.5\mingw530_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
build_script:
  - qmake QtTest.pro
  - ls
