version: 1.0.{build}
branches:
  only:
    - appveyor
image:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017
  - Ubuntu
install:
  - set QTDIR=C:\Qt\5.5\msvc2013_64
  - set PATH=%PATH%;%QTDIR%\bin;
build_script:
  - qmake OpenBoard.pro
  - nmake
