version: 1.0.{build}

branches:
  only:
    - appveyor

shallow_clone: true
clone_depth: 1

image:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017
  - Ubuntu

environment:
  VSVER: 18.0
  matrix:
    - QTDIR: C:\Qt\5.5\msvc2013
      cname: Win32-VS2013
    - QTDIR: C:\Qt\5.5\msvc2013_64
      cname: Win64-VS2013
    - QTDIR: C:\Qt\5.6\msvc2013
      cname: Win32-VS2013
    - QTDIR: C:\Qt\5.6\msvc2013_64
      cname: Win64-VS2013
    - QTDIR: C:\Qt\5.6.3\msvc2015
      cname: Win32-VS2015
    - QTDIR: C:\Qt\5.6.3\msvc2015_64
      cname: Win64-VS2015


matrix:
  fast_finish: true

install:
  - ps: $env:VSCOMNTOOLS=(Get-Content ("env:VS" + "$env:VSVER" + "0COMNTOOLS"))
  - set QTDIR=C:\Qt\5.5\msvc2013_64
  - set PATH=%PATH%;%QTDIR%\bin;
  - call "%VSCOMNTOOLS%\..\..\VC\vcvarsall.bat" x86_amd6
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'

build_script:
  - qmake OpenBoard.pro
  - nmake
