version: 1.0.{build}

branches:
  only:
    - appveyor

shallow_clone: true
clone_depth: 1

environment:
  VSVER: 18.0
  matrix:
    - QTDIR: C:\Qt\5.5\msvc2013
      cname: Win32-VS2013
    - QTDIR: C:\Qt\5.5\msvc2013_64
      cname: Win64-VS2013
    - QTDIR: C:\Qt\5.6\msvc2013
      cname: Win32-VS2013
    - QTDIR: C:\Qt\5.6\msvc2013_64
      cname: Win64-VS2013
    - QTDIR: C:\Qt\5.6.3\msvc2015
      cname: Win32-VS2015
    - QTDIR: C:\Qt\5.6.3\msvc2015_64
      cname: Win64-VS2015


matrix:
  fast_finish: true

install:
  - ls C:\Qt\5.5
  - '%QTDIR%\bin\qtenv2.bat'
  - if %QTDIR:_64=%==%QTDIR% ( set ARCH=x86 ) else set ARCH=x64
  - if %cname%==mingw set make=mingw32-make.exe
  - if %cname%==mingw g++ --version
  - if %cname%==mingw %make% --version
  - if not %cname%==mingw call "%ProgramFiles(x86)%\Microsoft Visual Studio %VSVER%\VC\vcvarsall.bat" %ARCH%
  - if not %cname%==mingw set make=nmake.exe
  - if not %cname%==mingw %make% /? > nul
  - if %cname%==mingw set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
#  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'

build_script:
  - qmake OpenBoard.pro
  - nmake
