version: 1.0.{build}

branches:
  only:
    - appveyor

shallow_clone: true
clone_depth: 1

image:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017
  - Ubuntu

install:
  - ps: $env:VSCOMNTOOLS=(Get-Content ("env:VS" + "$env:VSVER" + "0COMNTOOLS"))
  - set QTDIR=C:\Qt\5.5\msvc2013_64
  - set PATH=%PATH%;%QTDIR%\bin;
  - call "%VSCOMNTOOLS%\..\..\VC\vcvarsall.bat" x86_amd6
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'

build_script:
  - qmake OpenBoard.pro
  - nmake
