language: cpp

branches:
  only:
  - master

os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx

dist:
  - xenial

compiler:
  - gcc

# packages umtimediawidgets webkitwidgets multimedia uitools xmlpatterns script svg webkit
addons:
  apt:
    packages:
      - qt5-default
      - qtbase5-dev
      - qtscript5-dev
      - qttools5-dev
      - qtmultimedia5-dev
      - libqt5xmlpatterns5-dev
      - libqt5webkit5-dev
      - libqt5svg5-dev
      - libquazip5-dev
      - libquazip5-headers
      - libssl-dev
      - libpoppler-private-dev
      - libpoppler-cpp-dev
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - libpaper-dev
      - libbz2-dev
      - liblzma-dev
      - libass-dev
      - libopus-dev
      - libogg-dev
      - libx264-dev
      - libvorbis-dev
      - libtheora-dev
      - libvpx-dev
      - libmp3lame-dev
      - libsdl-dev
      - libxcb-shm0-dev
      - libva-dev
      - libfdk-aac-dev
  homebrew:
    packages:
      - qt
      - ffmpeg
      - openssl
      - quazip

before_install:

script:
  - qmake OpenBoard.pro
  - make all
  
  
