language: cpp

branches:
  only:
  - master

os:
  - linux

dist:
  - xenial

compiler:
  - gcc

# packages umtimediawidgets webkitwidgets multimedia uitools xmlpatterns script svg webkit
addons:
  apt:
    packages:
      - qt5-default
      - qtbase5-dev
      - qtscript5-dev
      - qttools5-dev
      - qtmultimedia5-dev
      - libqt5xmlpatterns5-dev
      - libqt5webkit5-dev
      - libqt5svg5-dev
      - libquazip5-dev
      - libquazip5-headers
      - libssl-dev
      - libpoppler-private-dev

before_install:

script:
  - qmake USE_SYSTEM_QUAZIP=1 OpenBoard.pro
  - make all
  
  
