language: cpp

branches:
  only:
  - master

os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx

dist:
  - xenial

compiler:
  - gcc

# packages umtimediawidgets webkitwidgets multimedia uitools xmlpatterns script svg webkit
addons:
  apt:
    packages:
      - qt5-default
      - qtbase5-dev
      - qtscript5-dev
      - qttools5-dev
      - qtmultimedia5-dev
      - libqt5xmlpatterns5-dev
      - libqt5webkit5-dev
      - libqt5svg5-dev
      - libquazip5-dev
      - libquazip5-headers
      - libssl-dev
      - libpoppler-private-dev
      - libpoppler-cpp-dev
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - libpaper-dev
      - libbz2-dev
      - liblzma-dev
      - libass-dev
      - libopus-dev
      - libogg-dev
      - libx264-dev
      - libvorbis-dev
      - libtheora-dev
      - libvpx-dev
      - libmp3lame-dev
      - libsdl-dev
      - libxcb-shm0-dev
      - libva-dev
      - libfdk-aac-dev
# homebrew:
#   packages:
#     - ffmpeg
#     - openssl
#     - quazip
#     - poppler

install:
  - |-
    if [ $TRAVIS_OS_NAME = osx ]; then 
      brew update
      cd $( brew --prefix )/Homebrew/Library/Taps/homebrew/homebrew-core
      git fetch --unshallow
      git checkout 9ba3d6ef8891e5c15dbdc9333f857b13711d4e97 # Formula/qt@5.5.rb
      brew install qt@5.5 
      brew install poppler quazip openssl ffmpeg
      brew link --force qt@5.5
    fi

script:
  - qmake OpenBoard.pro
  - make all
  
  
